### ISSUE TITLE
Error while using the package  node_modules/moment/moment.js: require() must have a single string literal argument. 

### ISSUE THREAD

**Issue by jpca999** [mmazzarolo/react-native-modal-datetime-picker#104]
![image](https://user-images.githubusercontent.com/1026325/31946817-db17048a-b8a0-11e7-87ec-f32070e4f184.png)

package version:  "react-native-modal-datetime-picker": "^4.11.0",

### When reporting a bug, please be sure to check if the issue still persists with react-native original date/time pickers:
Under the hood `react-native-modal-datetime-picker` uses react-native original [DatePickerAndroid](https://facebook.github.io/react-native/docs/datepickerandroid.html), [TimePickerAndroid](https://facebook.github.io/react-native/docs/timepickerandroid.html) and [DatePickerIOS](https://facebook.github.io/react-native/docs/datepickerios.html).    
Before reporting a bug, try swapping `react-native-datetime-picker` with react-native original date/time pickers to check if the problem persists.  

### When reporting a bug, please be sure to include the following:
- [ ] The outcome of the `react-native-modal-datetime-picker` swap described above
- [ ] A descriptive title
- [ ] An *isolated* way to reproduce the behavior (example: GitHub repository with code isolated to the issue that anyone can clone to observe the problem)
- [ ] What version of `react-native-modal-datetime-picker` you're using, and the platform(s) you're running it on (iOS, Android, device)
- [ ] What packages or other dependencies you're using
- [ ] The behavior you expect to see, and the actual behavior

### When you open an issue for a feature request, please add as much detail as possible:
- [ ] A descriptive title
- [ ] A description of the problem you're trying to solve, including *why* you think this is a problem
- [ ] An overview of the suggested solution
- [ ] If the feature changes current behavior, reasons why your solution is better

**Comment by mmazzarolo** [comment]
Please make sure you're actually using `v4.12.0`, [since this issue has been solved recently](https://github.com/mmazzarolo/react-native-modal-datetime-picker/pull/92)

**Comment by jpca999** [comment]
It used to work fine until i updated the expo version. 

this is what im using  
"react-native-modal-datetime-picker": "^4.13.0",
should i revert back ?

**Comment by jpca999** [comment]
@mmazzarolo   I also tried by changing the version to this.. 

"react-native-modal-datetime-picker": "4.12.0",

but I still get the error. 

here are my other pakcages, 
"react-native": "https://github.com/expo/react-native/archive/sdk-22.0.1.tar.gz",
"expo": "^22.0.0",
"react": "16.0.0-beta.5",

**Comment by camnicklaus** [comment]
@jpca999 did you ever get this sorted? I'm just trying to use moment.js and/or react-moment lib and getting the same error

**Comment by jpca999** [comment]
@camnicklaus   not yet, but if you look for this issue on the expo i think they have it solved usign something like tihs. 


    "react-redux": "^5.0.6",
    "redux": "^3.7.2",
    "redux-form": "^5.0.1",
    "redux-persist": "^4.9.1",
    "redux-thunk": "^2.2.0"
  },
  "resolutions": {
    "moment": "2.19.1"
  }
}
