### ISSUE TITLE
Styling bug with inline display in datetime mode

### ISSUE THREAD

**Issue by ajimae** [mmazzarolo/react-native-modal-datetime-picker#672]
## Environment
MacBook, Running MacOS 12.5.1

## Platforms
iOS

## Versions

- Android:
- iOS: 16.1
- react-native-modal-datetime-picker: 14.0.0
- [react-native-community/datetimepicker](https://github.com/react-native-community/datetimepicker): [6.1.3, 6.7.0, 6.3.2]
- react-native: 0.70.4
- react: 18.1.0

## Description
There is a bug with the styling for time in `inline` display mode.

[This is a related issue](https://github.com/mmazzarolo/react-native-modal-datetime-picker/issues/666), however downgrading didn't fix the issue for me.

![Screen Shot 2022-11-16 at 19 07 54](https://user-images.githubusercontent.com/32770340/202260068-366539e9-199c-4562-9197-b59c97e98114.png)

**Comment by felippewick** [comment]
Same here

**Comment by marcofuentes05** [comment]
Same here, it even looks worse because the user can't even see the time 
<img width="450" alt="image" src="https://user-images.githubusercontent.com/40815025/223563748-fae5b7dd-6d91-4c75-bd42-b0d2a8c392f8.png">

**Comment by fobos531** [comment]
Hey @mmazzarolo !

After some investigation, I've tracked down the issue to this https://github.com/react-native-datetimepicker/datetimepicker/pull/693 <-- the linked PR provides the means to fix it. I'm not exactly sure what broke it, but it seems in the more recent versions it is necessary to specify the height of the native inline datetime picker for the time to be displayed correctly. For example, this is the unwanted behaviour without any modifications 
![CleanShot 2023-04-05 at 19 44 14](https://user-images.githubusercontent.com/19533289/230161269-243a0879-2803-4fe9-824a-84be7329f3d0.png)

And If I do this:
```
   <PickerComponent
              display={display || "spinner"}
              {...otherProps}
              value={this.state.currentDate}
              onChange={this.handleChange}
              style={{ height: otherProps.mode === "datetime" && display === "inline" ? 370 : undefined }}
            />
```
in `DateTimePickerModal.ios.js`, then it seems to produce the desired behaviour, as seen below:
![CleanShot 2023-04-05 at 19 45 38](https://user-images.githubusercontent.com/19533289/230161599-25095952-e22f-437e-b6e0-71ef9db728a4.png)

I've found the 370 height to be a sweet spot for the datetime picker to correctly display the time component of the picker. Also, this only seems to be an issue when the underlying datetime picker is shown within a react-native `Modal`, in other cases it works fine with this workaround. 

Do you feel this is a "good-enough" solution for this issue? If yes, I'd be happy to submit a PR proposing this change.

**Comment by mmazzarolo** [comment]
Hey @fobos531 ! Thanks so much for the investigation, great detective work!
Yeah, your solution feels good-enough for this issue and a PR would be awesome. I'll release it as a major breaking change.
Two things to take into account when submitting a PR:
- Let's [bump the community picker peer dep](https://github.com/mmazzarolo/react-native-modal-datetime-picker/blob/83363d79224dca76f235cd08af59bd6dbeae461e/package.json#L53) version to be at least >= to the one shipped by the [PR you linked](https://github.com/react-native-datetimepicker/datetimepicker/pull/693) (just to make sure we're not breaking the experience on older versions of the community picker.
- If you could add some comments on the `370` magic number to explain that it seems to be a sweetspot and link this issue in the comments, that would be awesome. 

For a moment I even thought about making that number a prop, but I think this is something we should take care ourselves in this lib. 

Again, thanks so much for your investigation 🙇

**Comment by mmazzarolo** [comment]
Fixed by #697

**Comment by JestemTrzcinska** [comment]
Hi! I still encounter this bug...

Simulator iPhone 15 Pro Max:
<img width="322" alt="image" src="https://github.com/mmazzarolo/react-native-modal-datetime-picker/assets/38797647/83dacb6a-5b79-4c1c-9cdd-e8c007c3d4f3">
Simulator iPad Pro:
<img width="809" alt="image" src="https://github.com/mmazzarolo/react-native-modal-datetime-picker/assets/38797647/bbea6f78-5140-4fb9-83cf-7dfbc1173530">

"react-native-modal-datetime-picker": "^17.1.0"

**Comment by cunneen** [comment]
For those (like me) still encountering this issue, adding this prop helped me:

```jsx
    pickerComponentStyleIOS={{ height: 420}}
```
